const imag1 = "/pic1.png";
const imag2 = "/pic2.png";
const imag3 = "/pic3.png";
const imag4 = "/pic4.png";
const imag5 = "/pic5.png";
const imag6 = "/pic6.png";
const imag7 = "/pic7.png";
const imag8 = "/pic8.png";
export const patients = [
    {
        patientId: "P566",
        firstName: "Dheeraj",
        lastName: "Kumar",
        dob: "2005-02-06",
        sex: "Male",
        email: "dheerajkum838@gmail.com",
        phone: "03173909816",
        address1: "Sbhs",
        address2: "Shshhs",
        city: "Sbhshd",
        state: "CA",
        zip: "12345",
        height: "5.9",
        weight: "214",
        startingWeight: "210",
        currentWeight: "185",
        goalWeight: "165",
        weightChange12m: "-25",
        bmi: "27.3",
        bloodPressure: "120/80",
        heartRate: "72",
        allergyList: "hello world",
        medicineAllergy: "yes",
        diagnosis: "byvctc",
        disqualifiers: "nbubivyi",
        majorSurgeries: "yes",
        bariatricSurgery: "yes",
        surgeryList: "hwllb, jbdihcv ,dbh",
        takingMedication: "no",
        weightLossMeds12m: "jvhcgu",
        weightLossPrograms: "hviyctct",
        thyroidCancerHistory: "no",
        glp1: "Tirzepatide",
        glpTaken: "yes",
        glpRecentInjection: "no",
        semaglutideDose: "1.00",
        semaglutideUnit: "mg/2ml",
        semaglutideLastDose: "dose2",
        semaglutideRequestedDose: "dose2",
        tirzepatideDose: "10.00",
        tirzepatideUnit: "mg/2ml",
        tirzepetideDosingSchedule: "biweekly",
        tirzepetideLastDose: "dose2",
        tirzepetideRequestedDose: "dose2",
        tirzepetidePlanPurchased: "plan2",
        tirzepetideVial: "vial2",
        medicine: "Tirzepatide",
        approvalStatus: "",
        providerNote: "j hc h ch",
        providerComments: "h g ",
        images: [
            { preview: imag1, name: "img1" },
            { preview: imag2, name: "img2" },
            { preview: imag3, name: "img3" }
        ]

    },
    {
        patientId: "P567",
        firstName: "Ayesha",
        lastName: "Khan",
        dob: "1998-04-15",
        sex: "Female",
        email: "ayesha.khan@example.com",
        phone: "03111234567",
        address1: "Street 12",
        address2: "House 56",
        city: "Karachi",
        state: "Sindh",
        zip: "74400",
        height: "5.6",
        weight: "198",
        startingWeight: "205",
        currentWeight: "190",
        goalWeight: "160",
        weightChange12m: "-15",
        bmi: "30.2",
        bloodPressure: "130/85",
        heartRate: "76",
        allergyList: "pollen",
        medicineAllergy: "no",
        diagnosis: "diabetes",
        disqualifiers: "",
        majorSurgeries: "no",
        bariatricSurgery: "no",
        surgeryList: "",
        takingMedication: "yes",
        weightLossMeds12m: "Metformin",
        weightLossPrograms: "Yoga, Diet Plan",
        thyroidCancerHistory: "no",
        glp1: "Semaglutide",
        glpTaken: "no",
        glpRecentInjection: "no",
        semaglutideDose: "15.00",
        semaglutideUnit: "mg/3ml",
        semaglutideLastDose: "dose1",
        semaglutideRequestedDose: "dose2",
        tirzepatideDose: "30.00",
        tirzepatideUnit: "mg/2ml",
        tirzepetideDosingSchedule: "",
        tirzepetideLastDose: "",
        tirzepetideRequestedDose: "",
        tirzepetidePlanPurchased: "",
        tirzepetideVial: "",
        medicine: "Metformin",
        approvalStatus: "approved",
        providerNote: "Patient progressing well",
        providerComments: "Recommended light cardio",
        images: [
            { preview: imag4, name: "img1" },
            { preview: imag5, name: "img2" },
            { preview: imag6, name: "img3" }
        ]
    },
    {
        patientId: "P568",
        firstName: "Ali",
        lastName: "Zafar",
        dob: "1987-12-23",
        sex: "Male",
        email: "ali.zafar@example.com",
        phone: "03001234567",
        address1: "Apt 9",
        address2: "Hillview Road",
        city: "Lahore",
        state: "Punjab",
        zip: "54000",
        height: "6.0",
        weight: "250",
        startingWeight: "270",
        currentWeight: "245",
        goalWeight: "200",
        weightChange12m: "-25",
        bmi: "32.5",
        bloodPressure: "140/90",
        heartRate: "80",
        allergyList: "",
        medicineAllergy: "no",
        diagnosis: "Hypertension",
        disqualifiers: "",
        majorSurgeries: "yes",
        bariatricSurgery: "no",
        surgeryList: "Gallbladder removal",
        takingMedication: "yes",
        weightLossMeds12m: "Tirzepatide",
        weightLossPrograms: "Gym",
        thyroidCancerHistory: "no",
        glp1: "Tirzepatide",
        glpTaken: "yes",
        glpRecentInjection: "yes",
        semaglutideDose: "25.00",
        semaglutideUnit: "mg/5ml",
        semaglutideLastDose: "",
        semaglutideRequestedDose: "",
        tirzepatideDose: "30.00",
        tirzepatideUnit: "mg/2ml",
        tirzepetideDosingSchedule: "weekly",
        tirzepetideLastDose: "dose1",
        tirzepetideRequestedDose: "dose2",
        tirzepetidePlanPurchased: "plan1",
        tirzepetideVial: "vial1",
        medicine: "Tirzepatide",
        approvalStatus: "pending",
        providerNote: "Needs follow-up",
        providerComments: "Monitor BP closely",
        images: [
            { preview: imag7, name: "img1" },
            { preview: imag8, name: "img2" },
            { preview: imag4, name: "img3" }
        ]
    },
    {
        patientId: "P569",
        firstName: "Sara",
        lastName: "Ahmed",
        dob: "1995-09-10",
        sex: "Female",
        email: "sara.ahmed@example.com",
        phone: "03211234567",
        address1: "Block B",
        address2: "Model Town",
        city: "Islamabad",
        state: "ICT",
        zip: "44000",
        height: "5.5",
        weight: "160",
        startingWeight: "165",
        currentWeight: "155",
        goalWeight: "140",
        weightChange12m: "-10",
        bmi: "26.5",
        bloodPressure: "115/75",
        heartRate: "70",
        allergyList: "shellfish",
        medicineAllergy: "yes",
        diagnosis: "PCOS",
        disqualifiers: "",
        majorSurgeries: "no",
        bariatricSurgery: "no",
        surgeryList: "",
        takingMedication: "yes",
        weightLossMeds12m: "Semaglutide",
        weightLossPrograms: "Keto",
        thyroidCancerHistory: "no",
        glp1: "Semaglutide",
        glpTaken: "yes",
        glpRecentInjection: "no",
        semaglutideDose: "6.80",
        semaglutideUnit: "mg/2ml",
        semaglutideLastDose: "dose2",
        semaglutideRequestedDose: "dose2",
        tirzepatideDose: "60.00",
        tirzepatideUnit: "mg/2ml",
        tirzepetideDosingSchedule: "",
        tirzepetideLastDose: "",
        tirzepetideRequestedDose: "",
        tirzepetidePlanPurchased: "",
        tirzepetideVial: "",
        medicine: "Semaglutide",
        approvalStatus: "approved",
        providerNote: "Great progress",
        providerComments: "Maintain current routine",
        images: [
            { preview: imag5, name: "img1" },
            { preview: imag6, name: "img2" },
            { preview: imag8, name: "img3" }
        ]
    }
];
