import mongoose from "mongoose";

const PatientSchema = new mongoose.Schema({
    authid: {
        type: String,
        required: true,
        unique: true
    },
    patientId: String,
    firstName: String,
    lastName: String,
    dob: String,
    height: String,
    email: String,
    sex: String,
    weight: String,
    phone: String,
    glp1: String,
    bmi: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    zip: String,
    bloodPressure: String,
    heartRate: String,
    takingMedication: String,
    medicineAllergy: String,
    listAllMedication: String,
    allergyList: String,
    majorSurgeries: String,
    bariatricSurgery: String,
    thyroidCancerHistory: String,
    surgeryList: String,
    disqualifiers: String,
    diagnosis: String,
    startingWeight: String,
    currentWeight: String,
    goalWeight: String,
    weightChange12m: String,
    weightLossPrograms: String,
    weightLossMeds12m: String,
    glpTaken: String,
    glpRecentInjection: String,
    semaglutideLastDose: String,
    semaglutideRequestedDose: String,
    tirzepetideLastDose: String,
    tirzepetideRequestedDose: String,
    tirzepetidePlanPurchased: String,
    tirzepetideVial: String,
    tirzepetideDosingSchedule: String,
    providerComments: String,
    medicine: String,
    approvalStatus: String,
    semaglutideDose: String,
    semaglutideUnit: String,
    tirzepatideDose: String,
    tirzepatideUnit: String,
    providerNote: String,
    createTimeDate: String,
    closetickets: Boolean,
    Reasonclosetickets: String,
    images: [String],  // Array of image URLs
    file1: String,
    file2: String,
    questionnaire: {
        type: Boolean,
        default: false,
    },
    country: String,
    goalBmi: String,
    conditions: [String],
    familyConditions: [String],
    weightLossSurgery: [String],
    weightRelatedConditions: [String],
    medications: [String],
    kidneyDisease: String,
    diets: [String],
    otherConditions: String,
    currentMedications: String,
    pregnant: String,
    breastfeeding: String,
    healthcareProvider: String,
    eatingDisorders: String,
    labs: String,
    glp1Statement: String,
    glp1DoseInfo: String,
    agreeTerms: Boolean,
});

export const Patient = mongoose.models.Patient || mongoose.model("Patient", PatientSchema);