import mongoose from "mongoose";

const PatientSchema = new mongoose.Schema({
    authid: {
        type: String,
        required: true,
        unique: true
    },
    patientId: String,
    firstName: String,
    lastName: String,
    dob: String,
    height: String,
    email: String,
    sex: String,
    weight: String,
    phone: String,
    glp1: String,
    bmi: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    zip: String,
    bloodPressure: String,
    heartRate: String,
    takingMedication: String,
    medicineAllergy: String,
    listAllMedication: String,
    allergyList: String,
    majorSurgeries: String,
    bariatricSurgery: String,
    thyroidCancerHistory: String,
    surgeryList: String,
    disqualifiers: String,
    diagnosis: String,
    startingWeight: String,
    currentWeight: String,
    goalWeight: String,
    weightChange12m: String,
    weightLossPrograms: String,
    weightLossMeds12m: String,
    glpTaken: String,
    glpRecentInjection: String,
    semaglutideLastDose: String,
    semaglutideRequestedDose: String,
    tirzepetideLastDose: String,
    tirzepetideRequestedDose: String,
    tirzepetidePlanPurchased: String,
    tirzepetideVial: String,
    tirzepetideDosingSchedule: String,
    providerComments: String,
    medicine: String,
    approvalStatus: String,
    semaglutideDose: String,
    semaglutideUnit: String,
    tirzepatideDose: String,
    tirzepatideUnit: String,
    lipotropicDose: String,
    lipotropicUnit: String,
    providerNote: String,
    createTimeDate: String,
    closetickets: Boolean,
    Reasonclosetickets: String,
    images: [String],  // Array of image URLs
    file1: String,
    file2: String,
    questionnaire: {
        type: Boolean,
        default: false,
    },
    country: String,
    goalBmi: String,
    conditions: [String],
    familyConditions: [String],
    weightLossSurgery: [String],
    weightRelatedConditions: [String],
    medications: [String],
    kidneyDisease: String,
    diets: [String],
    otherConditions: String,
    currentMedications: String,
    pregnant: String,
    breastfeeding: String,
    healthcareProvider: String,
    eatingDisorders: String,
    labs: String,
    glp1Statement: String,
    glp1DoseInfo: String,
    agreeTerms: Boolean,
    followUp: String,         // e.g., "2025-08-23T00:27:44.386Z_7d"
    refillReminder: String,   // e.g., "2025-08-30T00:27:44.386Z_14d"
    // Additional Information / Marketing source
    heardAbout: {
        type: String,
        enum: ['Instagram', 'Facebook', 'TikTok', 'Other'],
        trim: true
    },
    heardAboutOther: {
        type: String,
        trim: true
    },
    // Lipotropic Fields
    lipotropicAllergies: [String],
    lipotropicAllergiesDrop: String,
    lipotropicGoals: [String],
    lipotropicHistory: String,
    lipotropicLastTreatment: String,
    lipotropicSatisfaction: String,
    lipotropicStopReason: String,
    averageMood: String,
    lipotropicDiagnoses: [String],
    lipotropicMedicalConditions: String,
    lipotropicMedicalConditionsDrop: String,
    lipotropicMeds: String,
    lipotropicMedsDrop: String,
    lipotropicPregnant: String,
    providerQuestions: String,
    providerQuestionsDrop: String,
    lipotropicConsent: Boolean,
    lipotropicTerms: Boolean,
    lipotropicTreatment: Boolean,
    lipotropicElectronic: Boolean,
    // GLP-1 Consent Fields
    bmiConsent: Boolean,
    consent: Boolean,
    terms: Boolean,
    treatment: Boolean,
    agreetopay: Boolean,
});

export const Patient = mongoose.models.Patient || mongoose.model("Patient", PatientSchema);